version: '3.6'

services:
  db:
    container_name: helgart_db
    image: mariadb:10.4.4-bionic
    restart: always
    ports:
      - "33104:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - helgart_db:/var/lib/mysql

  nginx:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: helgart_nginx
    image: helgart/nginx-dev:0.0.1
    restart: always
    links:
      - broker-dev:broker-dev
    ports:
      - "8000:80"
    volumes:
      - ./nginx/broker/dev/:/etc/nginx/conf.d/
      - ../../broker/public/:/usr/share/nginx/html/

  broker-dev:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db:db
    volumes:
        - ../../:/go/src/github.com/kaplanmaxe/helgart
    container_name: helgart_broker_dev
    image: helgart/broker-dev:0.0.1
    restart: always

volumes:
  helgart_db: