version: '3.6'

services:
  db:
    container_name: helgart_db
    image: mariadb:10.4.4-bionic
    restart: always
    ports:
      - "33104:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - helgart_db:/var/lib/mysql
  cache:
    container_name: helgart_cache
    image: redis:5.0.5-alpine
    ports:
      - "6350:6379"
    restart: always

  broker-dev:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db:db
      - cache:cache
    ports:
      - "3000:8080"
    volumes:
        - ../../:/go/src/github.com/kaplanmaxe/helgart
    container_name: helgart_broker_dev
    image: helgart/broker-dev:0.0.1
    restart: always

volumes:
  helgart_db: