language: go

go:
  - 1.12.4

services:
  - docker

script:
  - go get -u golang.org/x/lint/golint
  - make lint
  - make unit
  - make unit-race
  - make
  - make install
  - broker version
  - docker build -t helgart/broker .
  - docker run -ti --rm helgart/broker broker version