language: go

go:
  - 1.12.4

services:
  - docker

stages:
  - build
  - docker
  - test

jobs:
  include:
    name: build
    script:
      - make
      - make install
      - broker --version
    name: docker
    script:
      - make up
      - docker exec -ti helgart_broker helgart-broker --version
      - docker logs helgart_broker
      - make down
    name: test
    script:
      - go get -u golang.org/x/lint/golint
      - make lint
      - make unit
      - make unit-race
      - broker --version