version: '3.1'

services:
  broker:
    command: helgart-broker --config /home/.config.yml
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db:db
    volumes:
      - ./.config.docker.yml:/home/.config.yml
    container_name: helgart_broker
    image: helgart/broker:0.0.1
    restart: always
  
  db:
    container_name: helgart_db
    image: mariadb:10.4.4-bionic
    restart: always
    ports:
      - "33104:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - helgart_db:/var/lib/mysql
volumes:
  helgart_db:
