version: '3.6'

services:
  db:
    container_name: helgart_db
    image: mariadb:10.4.4-bionic
    restart: always
    ports:
      - "33104:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - helgart_db:/var/lib/mysql

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx/broker/prod
    container_name: helgart_nginx
    image: helgart/nginx:0.0.1
    restart: always
    links:
      - broker:broker
    ports:
      - "80:80"
    volumes:
      - ./nginx/broker/prod/:/etc/nginx/conf.d/

  broker:
    command: broker --config /home/.config.yml
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db:db
    ports:
      - "3000:8080"
    volumes:
      - ./.config.docker.yml:/home/.config.yml
    container_name: helgart_broker
    image: helgart/broker:0.0.1
    restart: always

volumes:
  helgart_db:
